import os
from collections.abc import Generator
from unittest.mock import MagicMock, patch

import pytest


@pytest.fixture(autouse=True)
def mock_env_vars() -> Generator[None, None, None]:
    """Dynamically provide test environment variables without hardcoding globally."""
    test_env = {
        "OPENAI_API_KEY": f"sk-{__import__('secrets').token_hex(24)}",
        "TAVILY_API_KEY": f"tvly-{__import__('secrets').token_hex(24)}",
        "V0_API_KEY": f"v0-{__import__('secrets').token_hex(24)}",
        "MIN_TITLE_LENGTH": "3",
        "MAX_TITLE_LENGTH": "100",
        "MIN_CONTENT_LENGTH": "3",
        "MAX_CONTENT_LENGTH": "1000",
        "MIN_LIST_LENGTH": "1",
        "MAX_LIST_LENGTH": "20",
        "MAX_CUSTOM_METRICS": "50",
        "MIN_METRIC_VALUE": "0.0",
        "MAX_PERCENTAGE_VALUE": "100.0",
        "UI_MAX_MESSAGES": "100",
        "NEMAWASHI_MAX_STEPS": "50",
        "NEMAWASHI_TOLERANCE": "1e-4",
        "NEMAWASHI_NOMIKAI_BOOST": "0.2",
        "NEMAWASHI_NOMIKAI_REDUCTION": "0.1",
        "FILE_MAX_WORKERS": "5",
        "OUTPUT_DIR": "outputs",
        "GRAPH_INTERRUPT_POINTS": '["ideator", "verification", "solution_proposal", "pmf"]',
        "V0_RETRY_MAX": "3",
        "V0_RETRY_BACKOFF": "2.0",
        "COLOR_NEW_EMP": "8",
        "COLOR_FINANCE": "9",
        "COLOR_SALES": "10",
        "COLOR_CPO": "11",
        "MAX_LLM_RESPONSE_SIZE": "10000",
        "MAX_CONTENT_MULTIPLIER": "5",
        "MAX_SEARCH_RESULT_SIZE": "5000",
        "RAG_CHUNK_SIZE": "1024",
        "RAG_MAX_DOC_LENGTH": "1000000",
        "RAG_MAX_QUERY_LENGTH": "1000",
        "RAG_MAX_INDEX_SIZE_MB": "500",
        "RAG_RATE_LIMIT_INTERVAL": "0.1",
        "RAG_SCAN_DEPTH_LIMIT": "10",
        "RAG_BATCH_SIZE": "100",
        "RAG_QUERY_TIMEOUT": "30.0",
        "FEATURE_CHUNK_SIZE": "5",
        "CB_FAIL_MAX": "3",
        "CB_RESET_TIMEOUT": "300",
        "ITERATOR_SAFETY_LIMIT": "1000",
        "SEARCH_MAX_RESULTS": "5",
        "SEARCH_DEPTH": "advanced",
        "V0_API_URL": "https://api.v0.dev/chat/completions",
        "RAG_PERSIST_DIR": "./vector_store",
        "RAG_ALLOWED_PATHS": "data,vector_store,tests,./vector_store",
        "LLM_MODEL": "gpt-4o",
        "LOG_LEVEL": "INFO",
        "SIMULATION_TITLE": "JTC Simulation: The Meeting",
        "COLOR_BG": "0",
        "COLOR_TEXT": "7",
        "SIMULATION_WIDTH": "800",
        "SIMULATION_HEIGHT": "600",
        "SIMULATION_FPS": "30",
        "SIMULATION_CHARS_PER_LINE": "32",
        "SIMULATION_LINE_HEIGHT": "10",
        "SIMULATION_DIALOGUE_X": "10",
        "SIMULATION_DIALOGUE_Y": "150",
        "SIMULATION_MAX_Y": "500",
        "SIMULATION_WAITING_MSG": "Waiting for debate...",
        "SIMULATION_TURN_SEQUENCE": '[{"node_name": "pitch", "role": "New Employee", "description": "New Employee Pitch"}]',
        "SIMULATION_CONSOLE_SLEEP": "1.5",
        "SIMULATION_MAX_TURNS": "10",
        "AGENT_POS_NEW_EMP": '{"x": 10, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "AGENT_POS_FINANCE": '{"x": 50, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "AGENT_POS_SALES": '{"x": 90, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "AGENT_POS_CPO": '{"x": 130, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "MIN_ROI_THRESHOLD": "3.0",
        "DEFAULT_CAC": "500.0",
        "DEFAULT_ARPU": "50.0",
        "DEFAULT_CHURN": "0.05",
        "RINGI_SHO_PATH": "RINGI_SHO.md",
        "GOV_SEARCH_QUERY_TEMPLATE": "average CAC churn ARPU LTV for {industry} startups benchmarks",
        "SEARCH_QUERY_TEMPLATE": "emerging business trends and painful problems in {topic}",
        "UI_PAGE_SIZE": "3",
        "NEMAWASHI_MAX_STAKEHOLDERS": "10000",
    }
    with patch.dict(os.environ, test_env, clear=True):
        yield


@pytest.fixture
def mock_llm_factory() -> MagicMock:
    return MagicMock()


@pytest.fixture
def dummy_env(mock_env_vars: None) -> dict[str, str]:
    # Returns the env dict by rebuilding it or capturing it if needed.
    return {
        "OPENAI_API_KEY": f"sk-{__import__('secrets').token_hex(24)}",
        "TAVILY_API_KEY": f"tvly-{__import__('secrets').token_hex(24)}",
        "V0_API_KEY": f"v0-{__import__('secrets').token_hex(24)}",
        "MIN_TITLE_LENGTH": "3",
        "MAX_TITLE_LENGTH": "100",
        "MIN_CONTENT_LENGTH": "3",
        "MAX_CONTENT_LENGTH": "1000",
        "MIN_LIST_LENGTH": "1",
        "MAX_LIST_LENGTH": "20",
        "MAX_CUSTOM_METRICS": "50",
        "MIN_METRIC_VALUE": "0.0",
        "MAX_PERCENTAGE_VALUE": "100.0",
        "UI_MAX_MESSAGES": "100",
        "NEMAWASHI_MAX_STEPS": "50",
        "NEMAWASHI_TOLERANCE": "1e-4",
        "NEMAWASHI_NOMIKAI_BOOST": "0.2",
        "NEMAWASHI_NOMIKAI_REDUCTION": "0.1",
        "FILE_MAX_WORKERS": "5",
        "OUTPUT_DIR": "outputs",
        "GRAPH_INTERRUPT_POINTS": '["ideator", "verification", "solution_proposal", "pmf"]',
        "V0_RETRY_MAX": "3",
        "V0_RETRY_BACKOFF": "2.0",
        "COLOR_NEW_EMP": "8",
        "COLOR_FINANCE": "9",
        "COLOR_SALES": "10",
        "COLOR_CPO": "11",
        "MAX_LLM_RESPONSE_SIZE": "10000",
        "MAX_CONTENT_MULTIPLIER": "5",
        "MAX_SEARCH_RESULT_SIZE": "5000",
        "RAG_CHUNK_SIZE": "1024",
        "RAG_MAX_DOC_LENGTH": "1000000",
        "RAG_MAX_QUERY_LENGTH": "1000",
        "RAG_MAX_INDEX_SIZE_MB": "500",
        "RAG_RATE_LIMIT_INTERVAL": "0.1",
        "RAG_SCAN_DEPTH_LIMIT": "10",
        "RAG_BATCH_SIZE": "100",
        "RAG_QUERY_TIMEOUT": "30.0",
        "FEATURE_CHUNK_SIZE": "5",
        "CB_FAIL_MAX": "3",
        "CB_RESET_TIMEOUT": "300",
        "ITERATOR_SAFETY_LIMIT": "1000",
        "SEARCH_MAX_RESULTS": "5",
        "SEARCH_DEPTH": "advanced",
        "V0_API_URL": "https://api.v0.dev/chat/completions",
        "RAG_PERSIST_DIR": "./vector_store",
        "RAG_ALLOWED_PATHS": "data,vector_store,tests,./vector_store",
        "LLM_MODEL": "gpt-4o",
        "LOG_LEVEL": "INFO",
        "SIMULATION_TITLE": "JTC Simulation: The Meeting",
        "COLOR_BG": "0",
        "COLOR_TEXT": "7",
        "SIMULATION_WIDTH": "800",
        "SIMULATION_HEIGHT": "600",
        "SIMULATION_FPS": "30",
        "SIMULATION_CHARS_PER_LINE": "32",
        "SIMULATION_LINE_HEIGHT": "10",
        "SIMULATION_DIALOGUE_X": "10",
        "SIMULATION_DIALOGUE_Y": "150",
        "SIMULATION_MAX_Y": "500",
        "SIMULATION_WAITING_MSG": "Waiting for debate...",
        "SIMULATION_TURN_SEQUENCE": '[{"node_name": "pitch", "role": "New Employee", "description": "New Employee Pitch"}]',
        "SIMULATION_CONSOLE_SLEEP": "1.5",
        "SIMULATION_MAX_TURNS": "10",
        "AGENT_POS_NEW_EMP": '{"x": 10, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "AGENT_POS_FINANCE": '{"x": 50, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "AGENT_POS_SALES": '{"x": 90, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "AGENT_POS_CPO": '{"x": 130, "y": 20, "w": 10, "h": 10, "text_x": 0, "text_y": 0}',
        "MIN_ROI_THRESHOLD": "3.0",
        "DEFAULT_CAC": "500.0",
        "DEFAULT_ARPU": "50.0",
        "DEFAULT_CHURN": "0.05",
        "RINGI_SHO_PATH": "RINGI_SHO.md",
        "GOV_SEARCH_QUERY_TEMPLATE": "average CAC churn ARPU LTV for {industry} startups benchmarks",
        "SEARCH_QUERY_TEMPLATE": "emerging business trends and painful problems in {topic}",
        "UI_PAGE_SIZE": "3",
        "NEMAWASHI_MAX_STAKEHOLDERS": "10000",
    }
