from collections.abc import Callable, Iterator
from typing import Any, Protocol

from pydantic import BaseModel

from src.domain_models.politics import InfluenceNetwork
from src.domain_models.simulation import Role
from src.domain_models.state import GlobalState


class IStateContext(Protocol):
    """Protocol for state access to break circular dependencies."""

    def __getattr__(self, name: str) -> Any: ...


class ILLMClient(Protocol):
    def invoke(self, prompt: Any) -> Any: ...
    def stream(self, prompt: Any) -> Iterator[Any]: ...
    def with_structured_output(self, schema: type[BaseModel]) -> "ILLMClient": ...


class IPromptTemplate(Protocol):
    def format(self, **kwargs: Any) -> Any: ...
    def __or__(self, other: Any) -> Any: ...


class IConfigurationService(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...
    def get_all(self) -> Any: ...  # Return the core Settings object


class IPDFGenerator(Protocol):
    def add_page(self, orientation: str = "") -> None: ...
    def set_font(self, family: str, style: str = "", size: float = 0) -> None: ...
    def cell(
        self,
        w: float = 0,
        h: float = 0,
        text: str = "",
        border: int = 0,
        ln: int = 0,
        align: str = "",
        fill: bool = False,
        link: str = "",
        new_x: str = "",
        new_y: str = "",
    ) -> None: ...
    def multi_cell(
        self, w: float, h: float, text: str, border: int = 0, align: str = "J", fill: bool = False
    ) -> None: ...
    def output(self, name: str = "", dest: str = "") -> str | bytearray: ...
    def add_font(
        self, family: str, style: str = "", fname: str = "", uni: bool = False
    ) -> None: ...
    def ln(self, h: float | str = "") -> None: ...


class ISearchClient(Protocol):
    def safe_search(self, query: str) -> str: ...
    def search(self, query: str) -> dict[str, Any]: ...


class INodeRegistry(Protocol):
    def get_node(self, name: str) -> Any: ...
    def register_node(self, name: str, func: Any) -> None: ...


class IGraphEngine(Protocol):
    def add_node(self, name: str, action: Callable[[Any], Any]) -> None: ...
    def add_edge(self, start_key: str, end_key: str) -> None: ...
    def set_entry_point(self, key: str) -> None: ...
    def compile(self, interrupt_after: list[str] | None = None) -> Any: ...


class IEmbeddingService(Protocol):
    pass


class IVectorStore(Protocol):
    def as_query_engine(self) -> Any: ...
    def insert_nodes(self, nodes: list[Any]) -> None: ...


class IInfluenceAnalyzer(Protocol):
    def map_affinities(self, network: InfluenceNetwork) -> dict[str, Any]: ...


class IConsensusEngine(Protocol):
    def calculate_new_opinions(self, network: InfluenceNetwork) -> list[float]: ...


class INomikaiSimulator(Protocol):
    def run_nomikai(self, network: InfluenceNetwork, budget: float) -> InfluenceNetwork: ...


class IAgent(Protocol):
    def run(self, state: GlobalState) -> dict[str, Any]: ...


class INemawashiEngine(Protocol):
    def calculate_consensus(self, network: InfluenceNetwork) -> list[float]: ...
    def identify_influencers(self, network: InfluenceNetwork) -> list[str]: ...


class IBuilderAgent(Protocol):
    def generate_spec(self, state: GlobalState) -> dict[str, Any]: ...
    def generate_experiment_plan(self, state: GlobalState) -> dict[str, Any]: ...
    def run(self, state: GlobalState) -> dict[str, Any]: ...


class ISimulationGraph(Protocol):
    def invoke(self, state: GlobalState) -> Any: ...


class IAgentFactory(Protocol):
    def get_ideator_agent(self) -> IAgent: ...
    def get_persona_generator_agent(self) -> IAgent: ...
    def get_alternative_analysis_agent(self) -> IAgent: ...
    def get_vpc_agent(self) -> IAgent: ...
    def get_mental_model_journey_agent(self) -> IAgent: ...
    def get_sitemap_wireframe_agent(self) -> IAgent: ...
    def get_virtual_customer_agent(self) -> IAgent: ...
    def get_3h_review_agent(self) -> IAgent: ...
    def get_builder_agent(self) -> IBuilderAgent: ...
    def get_governance_agent(self) -> IAgent: ...
    def get_persona_agent(self, role: Role, state: GlobalState) -> IAgent: ...


class IServiceFactory(Protocol):
    def get_configuration_service(self) -> IConfigurationService: ...
    def get_llm_client(self) -> ILLMClient: ...
    def get_search_client(self) -> ISearchClient: ...
    def get_pdf_generator(self) -> IPDFGenerator: ...
    def get_nemawashi_engine(self) -> INemawashiEngine: ...
    def get_simulation_graph(self) -> ISimulationGraph: ...
